# -*- coding:utf-8 -*-
# !/usr/bin/env python
# Time 18-6-29
# Author Yo
# Email YoLoveLife@outlook.com

# OPS PUSH_MISSION
STATUS_PUSH_MISSION_LACK_OF_KEY_OR_JUMPER = -3
STATUS_PUSH_MISSION_UNREACHABLE = -2
STATUS_PUSH_MISSION_FAILED = -1
STATUS_PUSH_MISSION_WAIT_EXAM = 1
STATUS_PUSH_MISSION_WAIT_UPLOAD = 2
STATUS_PUSH_MISSION_WAIT_RUN = 3
STATUS_PUSH_MISSION_RUNNING = 4
STATUS_PUSH_MISSION_SUCCESS = 5
STATUS_PUSH_MISSION_IMPORT_VAR = 6
STATUS_PUSH_MISSION_IMPORT_TASKS = 7
STATUS_PUSH_MISSION_RERUN = 8

# SAFE WORK
STATUS_SAFEWORK_REJECT = -1
STATUS_SAFEWORK_WAIT_RUN = 1
STATUS_SAFEWORK_WAIT_DONE = 2
STATUS_SAFEWORK_DONE = 3

# HOST
STATUS_HOST_DELETE = -5
STATUS_HOST_DENY_OR_REFUSE = -4
STATUS_HOST_NOT_SELECT = -3
STATUS_HOST_CLOSE = -2
# 此状态机器将不会参与到所有运维操作中
STATUS_HOST_PAUSE = -1
STATUS_HOST_CAN_BE_USE = 1
STATUS_HOST_DISK_SPACE_FULL = 2
STATUS_HOST_UPTIME_ERROR = 3
STATUS_HOST_DISK_INODE_FULL = 4

# GROUP
STATUS_GROUP_PAUSE = -2
STATUS_GROUP_UNREACHABLE = -1
STATUS_GROUP_CAN_BE_USE = 1

# JUMPER
STATUS_JUMPER_WRONG_KEY = -3
STATUS_JUMPER_NO_KEY = -2
STATUS_JUMPER_UNREACHABLE = -1
STATUS_JUMPER_CAN_BE_USE = 1

# EZSETUP STATUS
STATUS_EZSETUP_UNREACHABLE = -3
STATUS_EZSETUP_LACK_OF_KEY_OR_JUMPER = -2
STATUS_EZSETUP_ERROR = -1
STATUS_EZSETUP_INSTALLING = 1
STATUS_EZSETUP_DONE = 2

# CDN STATUS
STATUS_CDN_ERROR = -1
STATUS_CDN_RUN = 1
STATUS_CDN_DONE = 2


# CDN TYPE
TYPE_CDN_NONE = -1
TYPE_CDN_QN = 1
TYPE_CDN_WS = 2
TYPE_CDN_ALIYUN = 3

# EZSETUP TYPE
TYPE_EZSETUP_MYSQL = 1
TYPE_EZSETUP_REDIS = 2

# MONITOR TIME TYPE
TYPE_MONITOR_ONE_HOUR = 1
TYPE_MONITOR_SIX_HOUR = 2
TYPE_MONITOR_HALF_DAY = 3
TYPE_MONITOR_DAY = 4
TYPE_MONITOR_3_DAY = 5
TYPE_MONITOR_7_DAY = 6

# IP_POOL TYPE
TYPE_IP_POOL_ECS = 1
TYPE_IP_POOL_SLB = 2
TYPE_IP_POOL_DNAT = 3
TYPE_IP_POOL_SNAT = 4
TYPE_IP_POOL_WAF = 5
TYPE_IP_POOL_DDOS = 6


# DB INSTANCE
STATUS_DB_INSTANCE_CONNECT_REFUSE = -3
STATUS_DB_INSTANCE_PASSWORD_WRONG = -2
STATUS_DB_INSTANCE_UNREACHABLE = -1
STATUS_DB_INSTANCE_CAN_BE_USE = 1

# DB TYPE
TYPE_DB_INSTANCE_MASTER = 1
TYPE_DB_INSTANCE_SLAVE = 2
TYPE_DB_INSTANCE_MGR = 3

# SLOT TYPE
TYPE_SLOT_EXPIRE = 1
TYPE_SLOT_INSPECT = 2

# ASSET STATUS
STATUS_ASSET_SCRAP = -3
STATUS_ASSET_STOP = -2
STATUS_ASSET_LOCK = -1
STATUS_ASSET_DONE = 1

# ASSET CHANGE TYPE
TYPE_ASSET_CHANGE_CREATE = 0
TYPE_ASSET_CHANGE_UPDATE = 1
TYPE_ASSET_CHANGE_STOP = -1
TYPE_ASSET_CHANGE_SCRAP = -2

# ASSET_CHANGE CHANGE STATUS
STATUS_ASSET_CHANGE_INSTALL = 0
STATUS_ASSET_CHANGE_CONFIG = 1
STATUS_ASSET_CHANGE_CHECK = 2
STATUS_ASSET_CHANGE_DONE = 3

# WORKORDER TYPE
TYPE_WORKORDER_INACTIVE = 0
TYPE_WORKORDER_RUN = 1
TYPE_WORKORDER_DONE = 2

# Repository status
STATUS_REPOSITORY_EXPIRED = -2
STATUS_REPOSITORY_MAINTENANCE = -1
STATUS_REPOSITORY_OK = 1

# Kalendar
STATUS_KALENDAR_ONCALL = 3
STATUS_KALENDAR_LOOP = 2
STATUS_KALENDAR_NOTICE = 1
STATUS_KALENDAR_EVENT = -1
STATUS_KALENDAR_ERROR = -2

# Notice
STATUS_NOTICE_ONCALL = 3
STATUS_NOTICE_LOOP = 2
STATUS_NOTICE_NOTICE = 1
STATUS_NOTICE_EVENT = -1
STATUS_NOTICE_ERROR = -2

# Remind Type
STATUS_REMIND_SUCCESS = 1
STATUS_REMIND_INFO = 0
STATUS_REIND_WARN = -1
STATUS_REMIND_ERROR = -2

# TIMELINE_VALUE_KEY = {v: k for k, v in TIMELINE_KEY_VALUE.items()}